refactor: rework github deployment steps

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,4 +1,4 @@
-name: Homelab CI/CD
+name: Homelab Infrastructure Deployment
 
 on:
   push:
@@ -7,11 +7,19 @@ on:
   workflow_dispatch:
 
 jobs:
-  network-terraform:
-    name: Network Terraform
+  homelab-infra:
+    name: Homelab Infrastructure
     runs-on: ubuntu-latest
 
+    env:
+      TF_VAR_router_core_password: ${{ secrets.ROUTER_CORE_PASSWORD }}
+      TF_VAR_router_core_username: ${{ secrets.ROUTER_CORE_USERNAME }}
+      TF_VAR_router_core_host_url: "https://10.70.30.1"
+
     steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
       - name: Tailscale
         uses: tailscale/github-action@v3
         with:
@@ -23,18 +31,13 @@ jobs:
       - name: Verify Tailscale Connection
         run: |
           echo "Waiting for Tailscale to establish connection..."
-          # Wait for a short period to allow Tailscale to connect
           sleep 10
-          # Attempt to ping the target IP
           if ping -c 4 10.70.30.1 > /dev/null 2>&1; then
             echo "Ping to 10.70.30.1 successful."
           else
             echo "Ping to 10.70.30.1 failed. Exiting."
             exit 1
           fi
-
-      - name: Checkout Repository
-        uses: actions/checkout@v3
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
@@ -45,16 +48,13 @@ jobs:
 
       - name: Terraform Init
         run: terraform -chdir=deploy/terraform/ init
-        env:
-          TF_VAR_router_core_password: ${{ secrets.ROUTER_CORE_PASSWORD }}
-          TF_VAR_router_core_username: ${{ secrets.ROUTER_CORE_USERNAME }}
-          TF_VAR_router_core_host_url: https://10.70.30.1
 
-      - name: Terraform Format
+      - name: Terraform Format Check
         run: terraform -chdir=deploy/terraform/ fmt -check
 
-      - name: Write Network Terraform vars file from secret
-        run: echo "${{ secrets.TERRAFORM_VARS_NETWORK_B64 }}"  | base64 --decode > ./deploy/terraform/terraform.tfvars.json
+      - name: Write Network Terraform Vars File
+        run: |
+          echo "${{ secrets.TERRAFORM_VARS_NETWORK_B64 }}" | base64 --decode > ./deploy/terraform/terraform.tfvars.json
         shell: bash
 
       - name: Terraform Validate
@@ -63,28 +63,16 @@ jobs:
       - name: Terraform Plan
         id: plan
         run: terraform -chdir=./deploy/terraform/ plan -out=tfplan
-        env:
-          TF_VAR_router_core_password: ${{ secrets.ROUTER_CORE_PASSWORD }}
-          TF_VAR_router_core_username: ${{ secrets.ROUTER_CORE_USERNAME }}
-          TF_VAR_router_core_host_url: https://10.70.30.1
 
       - name: Terraform Apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
         run: terraform -chdir=./deploy/terraform/ apply -auto-approve tfplan
-        env:
-          TF_VAR_router_core_password: ${{ secrets.ROUTER_CORE_PASSWORD }}
-          TF_VAR_router_core_username: ${{ secrets.ROUTER_CORE_USERNAME }}
-          TF_VAR_router_core_host_url: https://10.70.30.1
 
       - name: Terraform Output
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
         run: |
           terraform -chdir=./deploy/terraform/ output -json current_vlan30_leases > ./dhcp_leases_by_node.json
           echo "Terraform output generated successfully."
-        env:
-          TF_VAR_router_core_password: ${{ secrets.ROUTER_CORE_PASSWORD }}
-          TF_VAR_router_core_username: ${{ secrets.ROUTER_CORE_USERNAME }}
-          TF_VAR_router_core_host_url: https://10.70.30.1
 
       - name: Install SSH Private Key
         run: |
@@ -92,23 +80,21 @@ jobs:
           echo "${{ secrets.HOMELAB_SSH_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
-      - name: Add current_lease IPs to known_hosts
+      - name: Add current lease IPs to known_hosts
         run: |
           JSON_FILE="./dhcp_leases_by_node.json"
 
-          if ! command -v jq &> /dev/null
-          then
-              echo "jq could not be found, installing..."
+          # Install jq if not present
+          if ! command -v jq &> /dev/null; then
+              echo "jq not found, installing..."
               sudo apt-get update && sudo apt-get install -y jq
           fi
 
           CURRENT_LEASE_IPS=$(jq -r '.[].current_lease' "$JSON_FILE" | sort -u)
-
           echo "Adding the following IPs to known_hosts:"
           echo "$CURRENT_LEASE_IPS"
 
           mkdir -p ~/.ssh
-
           touch ~/.ssh/known_hosts
 
           for IP in $CURRENT_LEASE_IPS; do
@@ -118,25 +104,21 @@ jobs:
 
           sort -u ~/.ssh/known_hosts -o ~/.ssh/known_hosts
 
-      - name: Run Python Script to Refresh DHCP Leases
-        run: |
-          python3 ./scripts/util/refresh-node-dhcp-lease.py ./dhcp_leases_by_node.json
+      - name: Refresh DHCP Leases via Python Script
+        run: python3 ./scripts/util/refresh-node-dhcp-lease.py ./dhcp_leases_by_node.json
 
       - name: Install Ansible Tools
         run: |
           python -m pip install --upgrade pip
-          pip install ansible
-          pip install ansible-lint
+          pip install ansible ansible-lint
 
       - name: Run Ansible Lint
-        run: |
-          pip install ansible-lint
-          ansible-lint deploy/ansible/homelab.yaml
+        run: ansible-lint deploy/ansible/homelab.yaml
 
       - name: Run Ansible Playbook
-        run: |
-          ansible-playbook -i ./deploy/ansible/inventory ./deploy/ansible/homelab.yaml --key-file ~/.ssh/id_rsa
+        run: ansible-playbook -i ./deploy/ansible/inventory ./deploy/ansible/homelab.yaml --key-file ~/.ssh/id_rsa
         env:
           PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
           BACKBLAZE_APPLICATION_KEY: ${{ secrets.BACKBLAZE_APPLICATION_KEY }}
           BACKBLAZE_KEY_ID: ${{ secrets.BACKBLAZE_KEY_ID }}
+
